[fix] 릴리즈 전 QA 이슈 수정
Team-Sopetit/Sopetit-Android pull request #139
Opened 2024-01-27 14:55 UTC by pump9918

## 📑 Work Description
- 뷰페이저 좌우 삭제
- 카드 전환 시 이전 스택 뷰 보이는 문제 해결
- 카드 로딩 전 기본이미지 placeholder 적용 및 로딩창 삭제

## 🛠️ Issue
- closed #138 

## 📷 Screenshot

https://github.com/Team-Sopetit/Sopetit-Android/assets/125239880/4ba519ff-af28-4d83-8b0b-3d00c7e1b20a

## 💬 To Reviewers
134번 머지 후에 받겠습니다

2024-01-28 08:37 UTC, stellar-halo requested changes
이미지 로딩이 느려서 고생이 많읍니다.. 저도 새로운 거 배워가요!
겹치는 코드가 많아 보이는데, 정말로 다 필요한 코드인지 확인해보시는 것도 좋을 것 같아보입니다.

2024-01-28 08:37 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
> +                }
acitivity에 이미 있는 코드인데 여기에도 적용해주어야 하나요?

2024-01-28 08:37 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.VISIBLE
혹시 이 부분 처리해주는 이유가 뭘까요? 하나의 activity안에 있는 단 하나의 layout이라 굳이 처리해줄 필요가 없어 보입니다.

2024-01-28 08:37 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.INVISIBLE
마찬가지입니다.

2024-01-28 08:46 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/detail/HappyDetailCardPagerAdapter.kt
> +                }
액티비티에는 star icon에 대한 placeholder이고, cardAdapter는 각 카드에 대한 placeholder입니다! 이 외에 delete Activity와 myRoutineFragment에도 placeholder가 되어 있을 텐데, 사용자가 카드가 다 로드 되기 전에 추가하기 버튼을 눌렀을 때의 임시 카드를 설정해놓기 위해서 넣어둔 겁니다!

2024-01-28 09:01 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.VISIBLE
https://github.com/Team-Sopetit/Sopetit-Android/assets/125239880/11a4abd8-28ec-499b-9a3e-d9d6c412eb29

setResult로 detailAcitivity -> AddListActivity -> MyRoutineActivity로 되돌아가는 구조인데, 이 과정에서 스택에 쌓여 있던 뷰들이 순간적으로 보여져 UX적으로 좋지 않다고 판단했습니다. onResume에 화면을 invisible 처리해두면 detailAcitivity에서 달성중 단계로 갈때 스택에 쌓인 뷰가 보이지 않아 매끄럽게 화면이 보였습니다.

2024-01-28 09:03 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.INVISIBLE
위와 동일한 이유로 순간적으로 보이는 뷰를 보이지 않게 처리해두었습니다. 이 방법이 바람직하지 않다면 다른 방식으로 찾아보겠습니다!

2024-01-29 15:23 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.VISIBLE
스택에 쌓여있는 뷰들을 정리해주는 Flag가 있습니다!
공부해보시고 적절한 Flag를 쓰면 해당 문제를 해결할 수 있어 보입니다!
https://vanillacreamdonut.tistory.com/156

2024-01-29 15:23 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.INVISIBLE
위에 답변 달았습니다!

2024-02-02 03:50 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/delete/HappyDeleteFragment.kt
> +                        placeholder(R.drawable.ic_bear_base)
placeholder는 drawble 파일을 바로 적용하는거라 로딩이 따로 느려질 이유는 없을 것 같은데 흠... 저도 한번 확인해보겠습니다.

2024-02-02 03:53 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.VISIBLE
감사합니다! 자료보고 정리해보도록 하겠습니다 :)

2024-02-02 14:06 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/ui/happyroutine/list/HappyAddListActivity.kt
> +        binding.clHappyAddList.visibility = View.VISIBLE
HappyAddListActivity에서는 별다른 조치 없이 DetailActivity로 넘어갈 때 finish()만 해주면 스택에 남지 않네요! 해결했습니다ㅎㅎ

2024-02-02 15:04 UTC, stellar-halo approved these changes
고생하셨습니다!

2024-02-02 15:10 UTC, merged