#135 [fix] 릴리즈 전 QA 이슈 수정
Team-Sopetit/Sopetit-Android pull request #146
Opened 2024-01-30 12:42 UTC by emjayMJkim

## 📑 Work Description
- 회원 탈퇴 뷰 3배수 이미지 변경 
- 리사이클러뷰 스크롤시 다중클릭 이슈 해결 

## 🛠️ Issue
- closed #135 

## 📷 Screenshot

## 💬 To Reviewers
이런저런 방법 써보고.. selection tracker도 써봤는데.. 결국 좀 허무하게 해결이 된 것 같네요.. 
일단 스크롤시 재사용으로 인한 다중클릭 이슈는 해결 했는데, 혹시나 다른 문제가 생기면 바로 해결하겠습니닷

2024-01-31 04:42 UTC, stellar-halo requested changes
뷰를 고친 부분이 있다면 꼭 다시 영상 첨부해주세요!!
고치느라 너무 고생했습니다..

2024-01-31 04:42 UTC, stellar-halo commented on app/src/main/res/layout/fragment_setting_user_exit.xml
> +            android:layout_height="208dp"
고정 dp 쓰지 마시고 margin으로 조정해주세요! 
+dimenRatio도 써서 조절해주세요~

2024-01-31 06:11 UTC, minemi00 approved these changes
애증의 리사이클러뷰.. 하느라 넘 고생하셨습니다..!!!!

2024-01-31 06:37 UTC, emjayMJkim commented on app/src/main/res/layout/fragment_setting_user_exit.xml
> +            android:layout_height="208dp"
넵!

2024-01-31 11:16 UTC, stellar-halo approved these changes
감사합니다,,

2024-01-31 11:16 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/onboarding/bearnaming/BearNamingFragment.kt
> +
감사합니다,,감사합ㄴ디ㅏ

2024-02-01 10:15 UTC, m1njae approved these changes
잔디 심으러 왔습니다.

2024-02-01 10:24 UTC, merged