Feature/#8 add daily routine
Team-Sopetit/Sopetit-Android pull request #18
Opened 2024-01-09 18:58 UTC by minemi00

## 📑 Work Description
- 데일리 루틴 추가하기 뷰 작업

## 🛠️ Issue
- closed #8 

## 📷 Screenshot

https://github.com/Team-Sopetit/Sopetit-Android/assets/145532333/1021f26a-eed8-40c8-a38b-b9f93830c88e

## 💬 To Reviewers
뷰페이저 양옆보이게.. 나중에 해볼게요 죽어도 안됨 ㅠ ( 호연오빠... 부탁해.. )

2024-01-10 07:00 UTC, pump9918 approved these changes
양옆 뷰페이저 저도 찾아보겠습니다... 고생했어요!

2024-01-10 07:00 UTC, pump9918 commented on app/build.gradle.kts
> +    //indicator
인디케이터 잘 쓰겠습니다^^

2024-01-12 15:03 UTC, minemi00 commented on app/build.gradle.kts
> +    //indicator
^^ 오빠가 기쁘니 좋다

2024-01-12 15:03 UTC, minemi00 commented on app/src/main/res/values/dimens.xml
> +<resources>
오빠 황금비율 대신 내가 가져옴ㅎ.ㅎ

2024-01-12 15:04 UTC, minemi00 commented on app/src/main/java/com/sopetit/softie/ui/daily/DailyAddActivity.kt
> +            outRect.left = divHeight
아하 ! 꼼꼼한 리뷰 감사합니다

2024-01-13 18:31 UTC, emjayMJkim approved these changes
뷰페이저 하느라 정말 수고했다...!!

2024-01-13 18:31 UTC, emjayMJkim commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
> +        }
강희언니 리뷰처럼 하나의 리스트로 처리해도 될 것 같습니다! 어처피 저희 routineId가 각각 themeId와 상관없이 모두 다르니까요...!!

2024-01-13 18:31 UTC, emjayMJkim commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
> +        }
여기 imageView background와 textView color 바꾸는 부분도 따로 함수로 빼주면 더 좋을 것 같습니다!

2024-01-13 18:31 UTC, emjayMJkim commented on app/src/main/res/layout/item_daily_routine_add_theme.xml
> +            <!--                app:layout_constraintTop_toTopOf="@id/iv_daily_routine_add_theme_background" />-->
삭제 부탁드립니닷...!

2024-01-14 03:11 UTC, stellar-halo requested changes
고생했어요~!~~!

2024-01-14 03:11 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
> +            setPadding(margin, 0, margin, 0)
이 친구들도 상수로 빼면 좋을 것 같아요!

2024-01-14 03:11 UTC, stellar-halo commented on app/src/main/res/layout/item_daily_routine_add_theme.xml
> +        <!--            tools:text="테마" />-->
역시 삭제 부탁드립니다!

2024-01-14 03:41 UTC, minemi00 commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
> +        }
아하 넵!

2024-01-14 03:44 UTC, minemi00 commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
> +        }
오 좋습니당!! 바꿔보겠슴당

2024-01-14 03:44 UTC, minemi00 commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddThemeAdapter.kt
> +        }
아하 넵!! 잘게잘게 쪼개볼게요

2024-01-14 03:47 UTC, minemi00 commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
> +            setPadding(margin, 0, margin, 0)
넵넵!

2024-01-14 05:08 UTC, minemi00 commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddActivity.kt
> +            it.offscreenPageLimit = 3
넵 한번 찾아보겠습니당

2024-01-14 13:52 UTC, stellar-halo approved these changes
고생했어요~

2024-01-14 13:52 UTC, stellar-halo commented on app/build.gradle.kts
> +    implementation("com.tbuonomo:dotsindicator:5.0")
여기 삭제해주세요~

2024-01-14 13:52 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineadd/DailyRoutineAddCardPagerAdapter.kt
> +            onItemsTheSame = { oldItem, newItem -> oldItem == newItem },
이 부분에 item이 고유한 값으로 지닌 값으로 비교해주세요~
예시로,

```suggestion
            onItemsTheSame = { oldItem, newItem -> oldItem.themeId == newItem.themeId },
```

2024-01-14 15:02 UTC, merged