#19 [ui] 데일리 루틴 뷰 구현
Team-Sopetit/Sopetit-Android pull request #34
Opened 2024-01-10 18:59 UTC by minemi00

## 📑 Work Description
- 데일리 루틴뷰 구현 완
- 데일리 루틴 편집 뷰 로직 빼고 완

## 🛠️ Issue
- closed #19 

## 📷 Screenshot

https://github.com/Team-Sopetit/Sopetit-Android/assets/145532333/673d6960-c9b4-4dfc-b6e7-6938616cff49

## 💬 To Reviewers
activity_sample 만들고 DailyEmptyActivity라는 가짜 액티비티 만들어서 확인해줬습니다.
편집 뷰에서 클릭한 개수대로 버튼 n개 삭제하기 텍스트 포함해서 편집용 브랜치에다가 로직 완성하겠습니다.

2024-01-10 19:36 UTC, stellar-halo requested changes
아자아자 화이팅!! 할 수 있다
GONE의 세계로,,

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/userdaily/DailyEditActivity.kt
> +    private var isBtnSelected = false
변수는 항상 class의 맨 상단에 주시면 됩니다!

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/userdaily/DailyEditActivity.kt
> +                btnRadioEmptyThird.isSelected = isBtnSelected
위의 변수를 공용으로 사용하고 있네요!
```
btnRadioEmpty.isSelected = !btnRadioEmpty.isSelected
```
이런식으로 바꿔주세요~!

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/userdaily/DailyEmptyFragment.kt
> +class DailyEmptyFragment :
Empty보다는 DailyRoutineFragment가 좀 더 어울려 보입니다!

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/userdaily/DailyEditActivity.kt
> +class DailyEditActivity : BindingActivity<ActivityDailyEditBinding>(R.layout.activity_daily_edit) {
DailyRoutineEditActivity는 어떤가요!
변수명이나 class명이 더 길어도 좋으니 명확하게 설명해주는 것이 좋아보입니다!

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/userdaily/DailyEmptyViewModel.kt
> +    }
empty fragment가 daily activity에 종속된 것이 아니니 viewModel을 분리해주세요!

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/res/layout/activity_daily_edit.xml
> +            android:id="@+id/tv_daily_routine"
tv_daily_routine_edit_routine 이런 식으로 바꿔주세요!
추가로 밑에 view들은 second 이런 식으로 인덱스가 붙으니 얘도 first를 붙여주는 것은 어떤가요?

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/res/layout/activity_daily_edit.xml
> +            android:id="@+id/tv_cancel"
마찬가지입니다~ id 컨벤션 지켜주세요!

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/res/layout/activity_daily_edit.xml
> +            android:id="@+id/v_blank"
ㅎㅎ

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/res/layout/activity_daily_edit.xml
> +
공백이 두 줄이네요 한 줄 삭제해주세요~

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/res/layout/activity_daily_edit.xml
> +            android:layout_height="57dp"
저는 고정 dp 보다는 height = "0dp"를 쓰고
paddingTop, paddingBottom을 이용하는 걸 더 선호하기는 합니다!

2024-01-10 19:36 UTC, stellar-halo commented on app/src/main/res/values/strings.xml
> +    <string name="daily_edit">편집</string>
뷰마다 분리해주세요!
<!-- daily routin -->
<!-- daily routin edit -->

string 변수명도 변경 부탁드립니다~

2024-01-11 06:17 UTC, stellar-halo approved these changes

2024-01-11 06:17 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
> +        const val FOURTH_ROUTINE = 4
너무 잦은 companion object는 좋지 않습니다!
companion object에서 const val는 컴파일 시에 초기화 되기 때문에 싱글톤으로 사용할 수 있는데,
위와 같은 변수들은 쓰이지 않을 가능성이 크며 다른 화면에서 필요해 보이지 않습니다! => companion으로 분류할 필요가 없어보입니다~

2024-01-11 06:17 UTC, stellar-halo commented on app/src/main/res/values/strings.xml
> +    <string name="doll_selection_button">이 친구와 함께 할래</string>
이 부분이 아마 bear selection으로 바뀌면서 잘못 merge된 거 같네요!

2024-01-11 06:25 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
> +        const val FOURTH_ROUTINE = 4
저도 무작정 썼는데 잘 배워갑니다!

2024-01-11 06:25 UTC, pump9918 approved these changes
올라가라~~

2024-01-11 06:32 UTC, emjayMJkim approved these changes
진짜 수고하셨습니다!!

2024-01-11 06:32 UTC, emjayMJkim commented on app/src/main/res/drawable/shape_white_fill_20_rect.xml
> +        android:width="1dp"/>
solid, stroke 색 다른 경우에는 파일명 `shape_white_fill_gray100_stroke_20_rect` 으로 바꿔주세요!

2024-01-11 06:32 UTC, emjayMJkim commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/dailyroutineedit/DailyRoutineEditActivity.kt
> +    private fun setButtonClickListener(button: View) {
함수화 좋아요~~

2024-01-11 06:44 UTC, merged