#66 [feat] 유저별 데일리루틴 리스트 조회 api 연결
Team-Sopetit/Sopetit-Android pull request #69
Opened 2024-01-16 08:07 UTC by minemi00

## 📑 Work Description
- 유저별 데일리루틴 리스트 조회 api 연결했습니다

## 🛠️ Issue
- closed #66 

## 📷 Screenshot

https://github.com/Team-Sopetit/Sopetit-Android/assets/145532333/012653c9-369e-485c-a354-64d670549d67

## 💬 To Reviewers
루틴 없을때 편집되는거랑 줄바꿈 이슈는 나중에 이슈파고 따로 해도 될까요 ^_ ㅠ

2024-01-16 15:34 UTC, stellar-halo requested changes
서버 처음이라 어려웠을텐데 고생했어요!

2024-01-16 15:34 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/data/repositoryImpl/DailyRoutineRepositoryImpl.kt
> +        runCatching { dailyRoutineDataSource.getDailyRoutine() }.mapCatching { response ->
mapCatching을 쓰셨군요! 👍
https://medium.com/harrythegreat/kotlin-runcatching%EA%B3%BC-result-%ED%83%80%EC%9E%85-ab261f47efa8
map과 mapCatching의 차이입니다~ 혹시나 하여 남기고 가요

2024-01-16 15:34 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineViewModel.kt
> +                    Timber.d("뷰모델 서버 실패")
삭제 부탁드립니다~

2024-01-16 15:38 UTC, minemi00 commented on app/src/main/java/com/sopetit/softie/data/repositoryImpl/DailyRoutineRepositoryImpl.kt
> +        runCatching { dailyRoutineDataSource.getDailyRoutine() }.mapCatching { response ->
아하 정독해보겠습니다!

2024-01-17 05:24 UTC, emjayMJkim approved these changes
서버 통신 수고하셨습니당

2024-01-17 05:24 UTC, emjayMJkim commented on app/src/main/java/com/sopetit/softie/domain/usecase/DeleteDailyRoutineUseCase.kt
> +    private val deleteDailyRoutine: DailyRoutineRepository
이 부분 변수 크게 상관은 없지만 dailyRoutineRespository 이런 식으로 repository를 받아온다는 걸 명확하게 하면 좀 더 좋을 것 같습니당

2024-01-17 05:24 UTC, emjayMJkim commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
> +
이 부분 함수는 왜 만들어 두신 건가요...??

2024-01-17 20:39 UTC, pump9918 approved these changes
서버와 연결되어 기쁩니다

2024-01-17 20:39 UTC, pump9918 commented on app/src/main/java/com/sopetit/softie/data/repositoryImpl/DailyRoutineRepositoryImpl.kt
> +            dailyRoutineDataSource.postAddDailyRoutine(routineId)
it대신 response로 그 위치를 명시해주라는 리드님의 말씀을 잘 지켰네요!

2024-01-17 20:47 UTC, stellar-halo approved these changes

2024-01-17 20:47 UTC, stellar-halo commented on app/src/main/java/com/sopetit/softie/ui/dailyroutine/DailyRoutineFragment.kt
> +        viewModel.isRoutineAchieveThird.observe(viewLifecycleOwner) {
요거는 왜 있나요~?

2024-01-17 20:48 UTC, merged